In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu121


In [102]:
# Scalars and vectors traditionally lowercase, while MATRICES and TENSORS are uppercase
scalar = torch.tensor(7)
scalar.ndim # Give dimensions
scalar.item() # Get tensor back as Python integer

vector = torch.tensor([7, 7]) # Size is default argument
vector.shape

MATRIX = torch.tensor([[1, 2],[3, 4]])
MATRIX[0] # First "element" of matrix = first row

TENSOR = torch.tensor([[[1, 2, 3],[4, 5, 6],[7, 7, 9]],
                      [[1, 2, 3],[4, 5, 6],[7, 7, 9]]])
TENSOR[0,1] == TENSOR[0][1] # Can index both ways

tensor([True, True, True])

In [103]:
random_tensor = torch.rand(3, 4) # Note ndim = 2, while (1, 3, 4) would be 3
random_image_size_tensor = torch.rand(size=(224,224,3)) # Height, width GGB

zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
ones.dtype # Float datatype by default

one_to_ten = torch.arange(start=0, end=11, step=1)
ten_zeros = torch.zeros_like(input=one_to_ten) # _like mimics shape of input

In [104]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], # Tensors must be right shape...
                    dtype = None,
                    device = None, # and on right device
                    requires_grad = False)

float_16_tensor = float_32_tensor.type(torch.float16)
int_32_tensor = float_16_tensor.type(torch.int32)

int_32_tensor.dtype # Three ways to find common tensor issues
int_32_tensor.device
int_32_tensor.shape

print(f"Data type of tensor: {int_32_tensor.dtype}")

Data type of tensor: torch.int32


In [105]:
%%time
# Tensor operations

tensor = torch.tensor([1,2,3])
tensor += 10
torch.mul(tensor, 10)
torch.div(tensor, 10)
torch.matmul(tensor, tensor) # Rely on built-in PyTorch functions for speed
# Inner dimensions must match, and output will have outer dimensions

tensorA = torch.tensor(([1,2],
           [3,4],
           [5,6]))
tensorA.T.shape

CPU times: user 738 µs, sys: 0 ns, total: 738 µs
Wall time: 2.32 ms


torch.Size([2, 3])

In [106]:
x = torch.arange(0, 100, 10)
torch.mean(x.type(torch.float32)) # Can also find min/max, like NumPy
torch.argmax(x) # Index of maximum, same for argmin

# View shows tensor in different shape, but keeps same memory as original
# Stack combines multiple tensors
# Squeeze removes all '1' dimensions from tensor
# Unsqueeze adds '1' dimension to tensor
# Permute returns view of input with swapped dimensions

x = torch.arange(1,11)
x.reshape(5, 2)
x.view(1,10)

x_stacked = torch.stack([x, x, x], dim=1)
torch.permute(x_stacked, (1,0)) # Another view

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [107]:
x = torch.arange(1,10).reshape(1,3,3)
x[0, 2, 1]

tensor(8)

In [15]:
array = np.arange(1,8)
tensor = torch.from_numpy(array) # Note that PyTorch and NumPy have different default types (flaoat32 and float64)

tensor2 = torch.ones(7) # PyTorch and NumPy don't share memory
tensor2.numpy()

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [20]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A == random_tensor_B)

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED) # Only works for the next block of notebook
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C == random_tensor_D)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [21]:
import torch

!nvidia-smi #Connected to GPU in Runtime settings
torch.cuda.is_available()

device = "cuda" if torch.cuda.is_available() else "cpu" # Device agnostic code

tensor = torch.tensor([1,2,3])
tensor.device

tensor_on_gpu = tensor.to(device)
another_tensor_on_gpu = torch.tensor([6,7,8], device = device)

# On a GPU, we cannot convert to NumPy
tensor_back_on_CPU = tensor_on_gpu.cpu()
tensor_back_on_CPU.numpy()

Sat Feb 24 04:37:44 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P0              29W /  70W |    105MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

array([1, 2, 3])